const AppConstants = {
	GET_NOTIF_CONFIG: "GET_NOTIF_CONFIG",
	UPDATE_NOTIF_CONFIG: "UPDATE_NOTIF_CONFIG",
	UPDATE_ALLNOTIF_STATUS: "UPDATE_ALLNOTIF_STATUS",
	UPDATE_STDTXT_STATUS:"UPDATE_STDTXT_STATUS",
	UPDATE_CUSTOM_TXT:"UPDATE_CUSTOM_TXT",
	UPDATE_ACTIVE_EMAIL:"UPDATE_ACTIVE_EMAIL"
};

export default AppConstants;
